toolbar_position:
  - 500
  - 850
  - 850
  - 150

gathering_position:
  - 640
  - 300
  - 500
  - 180

hotkeys:
  movement:
    north: w
    south: s
    west: a
    east: d
    north_west: q
    north_east: e
    south_west: z
    south_east: c

spells:
  increase_stamina:
    - hotkey: "f5"
      priority: 2
      needs_casting: False
      cast_time: 0
      target_anchor: ".\\target\\spells\\wind-arrow.jpg"

    - hotkey: "4"
      priority: 1
      needs_casting: False
      cast_time: 0
      target_anchor: ".\\target\\spells\\spirit-rangers.jpg"

  needs_stamina:
    - hotkey: "2"
      priority: 1
      needs_casting: False
      cast_time: 0
      target_anchor: ".\\target\\spells\\dragons-arrow.jpg"

    - hotkey: "1"
      priority: 2
      needs_casting: False
      cast_time: 0
      target_anchor: ".\\target\\spells\\precision-shot.jpg"

    - hotkey: "5"
      priority: 3
      needs_casting: False
      cast_time: 0
      target_anchor: ".\\target\\spells\\viper-arrow.jpg"

    - hotkey: "f5"
      priority: 4
      needs_casting: False
      cast_time: 0
      target_anchor: ".\\target\\spells\\wind-arrow.jpg"
      
