toolbar_position:
  - 500
  - 850
  - 850
  - 150

gathering_position:
  - 640
  - 300
  - 500
  - 180

map_position:
  - 1773
  - 173
  - 190
  - 190

hotkeys:
  movement:
    north: w
    south: s
    west: a
    east: d
    north_west: q
    north_east: e
    south_west: z
    south_east: c

spells:
  increase_stamina:
    - hotkey: "f5"
      priority: 1
      needs_casting: False
      cast_time: 0

    - hotkey: "4"
      priority: 2
      needs_casting: False
      cast_time: 0

  needs_stamina:
    - hotkey: "1"
      priority: 2
      needs_casting: False
      cast_time: 0

    - hotkey: "2"
      priority: 1
      needs_casting: False
      cast_time: 0

    - hotkey: "5"
      priority: 3
      needs_casting: False
      cast_time: 0

    - hotkey: "3"
      priority: 4
      needs_casting: False
      cast_time: 0

    - hotkey: "f5"
      priority: 5
      needs_casting: False
      cast_time: 0
      
